name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest

  build:
    strategy:
      matrix:
        go: [1.13, 1.14, 1.15, 1.16, 1.17]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{matrix.go}}

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -race -v -count=1 -coverprofile=coverage.out ./...

    - name: Upload Test Coverage
      uses: codecov/codecov-action@v2
      with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: ${{ matrix.go }}

      
